### ISSUE TITLE
CSS-解密

### ISSUE THREAD

**Issue by yaofly2012** [yaofly2012/note#181]
[探索 CSS 的本质](https://segmentfault.com/a/1190000025165025)

**Comment by yaofly2012** [comment]
# 盒模型

# 一、概念
表示元素的矩形盒子，由四部分构成。
![image](https://user-images.githubusercontent.com/6823623/100251682-fe5d2e80-2f79-11eb-87d2-67ea15d73d77.png)
[MDN CSS 基础框盒模型介绍](https://developer.mozilla.org/zh-CN/docs/Web/CSS/CSS_Box_Model/Introduction_to_the_CSS_box_model)里说的很详细里。
1. margin（外边距）区域
2. border（边框）区域
3. padding（内边距）区域
4. content（内容）区域

## 1.2 区域尺寸控制
margin, border, padding区域粗细（比用“大小”描述更形象些）有专门的CSS属性指定。但是确定content区域大小却复杂很多。

## 1.3 行内元素
非可替换元素行内元素高度由`line-height`指定。并且`margin/padding-top/bottom`是无效的。

## 1.4 宽高计算 & [box-sizing](https://developer.mozilla.org/zh-CN/docs/Web/CSS/box-sizing)
CSS里`width`, `height`, `max/min-width/height`属性指定的什么？
[CSS中width/height指的是什么？](https://github.com/yaofly2012/note/issues/148)

### 历史的兼容性
IE盒模型的差异

### [box-sizing](https://developer.mozilla.org/zh-CN/docs/Web/CSS/box-sizing)显示指定

## `display`
## margin合并




# 参考
1. [MDN CSS 基础框盒模型介绍](https://developer.mozilla.org/zh-CN/docs/Web/CSS/CSS_Box_Model/Introduction_to_the_CSS_box_model)

**Comment by yaofly2012** [comment]
# BFC(Block formatting context)
# 一、概念
一个区域，用于块盒模型布局，`float`元素和其他元素的关系。

布局互相独立，互不干扰

## 特性
1. 包含内部的`float`元素
即BFC不会因为`float`子元素导致高度坍塌。可以作为清除浮动的方式

2. 排除外部的`float`元素
BFC不会外部`float`元素发生重叠。可用于实现多列布局。

3. 禁止[`margin` 合并](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Box_Model/Mastering_margin_collapsing)

# 二、创建BFC
[MDN Block formatting context](https://developer.mozilla.org/en-US/docs/Web/Guide/CSS/Block_formatting_context)罗列了产生BFC的各种情况。

# 三、用法
BFC会影响布局，但是一般我们创建BFC是为了定位和清除浮动。

# FFC( Flex formatting context)/GFC(Grid formatting context)
1. 除了布局不同，其他同BFC
2. 不包含`float`子元素
3. 

# 参考
1. [MDN Block formatting context](https://developer.mozilla.org/en-US/docs/Web/Guide/CSS/Block_formatting_context)

**Comment by yaofly2012** [comment]
# 继承

# 求值过程
每个DOM元素的属性值的确定过程要经过4个阶段：
![image](https://user-images.githubusercontent.com/6823623/100560926-54bbcb80-32f2-11eb-9966-3a7936955c2a.png)

## 1.1 指定值【High】
指定值就是用户/作者定义的期望值（写在纸面上的，这一部分也是我们能控制的部分，也是重点研究的部分）。浏览器通过下面的 机制确定指定值：
![image](https://user-images.githubusercontent.com/6823623/100560946-60a78d80-32f2-11eb-92eb-b18c4b4c4842.png)

## 1.2 计算值
在层叠过程中会把指定值解析成计算值。比如把URI转成绝对地址，'em', 'pt'转成'px'单位的值。
## 1.3 使用值
DOM有些属性的值得等到布局时才能计算出来（比如指定值为百分比的宽度属性）。结合计算值和相关的依赖计算出的值就是使用值。
## 1.4 真实值
使用值都是用户希望的渲染结果，但是浏览器可以能有些限制。真实值就是DOM最终渲染后的真实值。

# 二、继承（Inheritance）
## 2.1 可继承性
有些属性值可以被子元素继承的（比如color, font-size等），关于属性是否可以被继承参考具体的属性说明。子元素继承的父元素的属性的计算值。

## 2.2 取值为'inherit'的属性
每个属性可以取值为‘inherit'，表示继承父元素的值。并且对于不可继承的属性如果取值是'inherit’，则强制继承父元素属性值。

# 三、@import规则
## 3.1 用处
@import规则用来导入外部CSS文件。
格式：@import '' | url('') [mediaType]+，多个媒介类型用逗号隔开。可以放在style元素和CSS文件中。
在style元素中：
```html
<style type="text/css">
@import 'index.css'; /* OR @import url('./index.css');*/
</style>
```
在CSS文件中：
```css
@import 'detail.css';
.c_order p{ /*0011*/
	color: red;
	background-color: #ccc
}
```
## 3.2 规则
1. @import必须放在其他样式声明之前，除了@charset规则，注释，以及其他@import规则。
```css
@import "subs.css"; 
h1 { color: blue }
@import "list.css"; /* 该@imprt无效，没有放在其他CSS声明之前 */
```

2. @import不能放在声明块中
```css
@media print {
  @import "print-main.css"; /* 无效，不能放在Block中 */
  body { font-size: 10pt }
}
```

3. 浏览器在解析时会忽略无效的@import规则。

## 3.3 与link的区别
两者在引入样式表的功能上没有区别，偏向使用link方式。
[What's the Difference Between @import and Link for CSS?](https://www.lifewire.com/difference-between-important-and-link-3466404)







# 参考
1. [CSS2 cascade](https://www.w3.org/TR/CSS2/cascade.html)

**Comment by yaofly2012** [comment]
# 层叠（Cascade）
于开发来说了解层叠的过程是必须的。先知道浏览器如何确定指定值，才能更好的指定CSS样式。确定样式依赖样式来源（Orgin），重要性（Importance），精确度（Specificity），出现先后。前3个因素构成样式的权重。层叠流程大致如：
![image](https://user-images.githubusercontent.com/6823623/100562047-6b175680-32f5-11eb-8f6b-a2ebaa858d63.png)

## 4.1 来源（Origin）& 重要性
一般样式有3个来源：浏览器默认样式，浏览器用户导入的样式，开发者指定的样式。他们的权重由小到大分别是：
A：浏览器默认样式
B：浏览器用户指定非important样式
C：页面作者指定的非important样式
D：页面作者指定的important样式
E：浏览器用户指定的important样式

 其中页面作者和浏览器用户指定的样式关系比较令人深思。浏览器采用一种平衡策略来平衡两者的关系。有些用户可能有一些特殊阅读需求（比如大号字体），浏览器也提供了该功能，即通过"!important"声明来提供声明权重。
```css
/* From the user's style sheet */
p { text-indent: 1em ! important } /* 覆盖页面作者的声明 */
p { font-style: italic ! important } /* 覆盖页面作者的声明 */
p { font-size: 18pt }


/* From the author's style sheet */
p { text-indent: 1.5em !important }
p { font: normal 12pt sans-serif !important }
p { font-size: 24pt } /* 覆盖用户的声明 */
```

## 4.2 精确度（Specificity）【High】
如果通过来源和重要性确定的权重相同，就得计算选择器的精确度，精确度越高权重越高。

1. 计算规则：
根据选择器的类型和样式来源分为四类：
a: style方式，
b: ID Selector，
c:属性选择器，类选择器，伪类选择器 
d:标签选择器，伪元素选择器。
这四类依照abcd的顺序构成一个数，该数字就是选择器的精确度（Specifity)，数字越大权重越大，采用权重大的选择器指定的样式，如果权重一样则后声明的覆盖先声明的。
2. a，b，c，d的取值规则：
A: a = 如果元素存在style声明的属性，则a=1, 否则a=0
B: b= 选择器中元素ID的数量
C: c=选择器中属性和（伪）类的数量
D: d=选择器中（伪）元素的数量
```css
*             {}  /* a=0 b=0 c=0 d=0 -> specificity = 0,0,0,0  什么也没有*/
 li            {}  /* a=0 b=0 c=0 d=1 -> specificity = 0,0,0,1  一个标签名*/
 li:first-line {}  /* a=0 b=0 c=0 d=2 -> specificity = 0,0,0,2 一个标签名，一个伪元素，故d=2*/
 ul li         {}  /* a=0 b=0 c=0 d=2 -> specificity = 0,0,0,2 两个标签名*/
 ul ol+li      {}  /* a=0 b=0 c=0 d=3 -> specificity = 0,0,0,3 三个标签名*/
 h1 + *[rel=up]{}  /* a=0 b=0 c=1 d=1 -> specificity = 0,0,1,1 一个标签名，一个属性名*/
 ul ol li.red  {}  /* a=0 b=0 c=1 d=3 -> specificity = 0,0,1,3 三个标签名，一个类名*/
 li.red.level  {}  /* a=0 b=0 c=2 d=1 -> specificity = 0,0,2,1 一个标签，两个类名*/
 #x34y         {}  /* a=0 b=1 c=0 d=0 -> specificity = 0,1,0,0 一个ID*/
 ul[id="list"] {}  /* a=0 b=0 c=1 d=1 -> specificity = 0,0,1,1 一个标签，一个属性。注意没有包含ID选择器，虽然属性里是判断ID的*/
 style=""          /* a=1 b=0 c=0 d=0 -> specificity = 1,0,0,0 style属性指定*/
```

4.3 出现先后
如果精确度也相同，则后出现的覆盖先出现的。
