### ISSUE TITLE
SASS

### ISSUE THREAD

**Issue by yaofly2012** [yaofly2012/note#56]
# 继承 PK 混合（Mixins）
一直搞混继承和混合。
所谓CSS继承就是一个class继承父class。Sass使用特殊的class命名方式标记父class，即`%`开头的class作为父class，所以父class也叫占位符class。
子class通过`@extend`指令指定继承的父class。
```scss
%message-shared {
  border: 1px solid #ccc;
  padding: 10px;
  color: #333;
}
.message {
  @extend %message-shared;
}
```
1. 没有被继承的父class不会生成最终的css；
2. 父class本质上是合法的class，只不过Sass特殊处理它了。
