### ISSUE TITLE
H5 --（解决）安卓的webview中line-height等于height不垂直居中问题

### ISSUE THREAD

**Issue by yaofly2012** [yaofly2012/note#73]
# 一、背景如题
参考这个文章[H5 --（解决）安卓的webview中line-height等于height不垂直居中问题](https://blog.csdn.net/weixin_41076513/article/details/79991866)，测试发现或多或少都还存在一些问题。
# 二、测试方案
## 2.1.  table布局方案
该方案还是存在兼容性问题
- 不行的机型：vivo(android 5.0)
- 可以的机型：oppo(android 5.1)

## 2.2 放大再缩小方案
因为缩写并不影响元素的布局，即元素占据的文档流没法缩小的。这种方案还是存在一定的局限性。参考的文档中也指出了>最佳实践：适用于单个或者是一排的布局
1. 使用流外布局（如float）消除放大占据的文档流；
2. 对于一排的元素列表，可以在父元素上进行放大缩小处理
不要在每个子元素上进行放大处理，免得造成布局问题。
```css
 .tag-list {
    line-height: 1em;
    /* float: left; */
    font-size: 20px;
    transform: scale(.5);
    transform-origin: 0 0;
    width: 200%;
}
.tag {
    background-image: linear-gradient(136deg,rgba(229,177,128,.4) 0,rgba(235,181,130,.4) 100%);
    border-radius: 16px;
    display: inline-block;
    color: #c18345;
    padding: 4px 12px;
    margin-right: 12px;
}
```
```html
<ul class="tag-list">
  <li class="tag">盒子1</li>
  <li class="tag">盒子盒子2</li>
  <li class="tag">盒子盒子盒子3</li>
  <li class="tag">盒子盒子盒子盒子4</li>
</ul>
```
![image](https://user-images.githubusercontent.com/6823623/66484896-6df42e00-eada-11e9-867a-5baece9aff2b.png)
